excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kaniabi.github.io
title: Alexandre Andrade
tagline: Auto Desenvolvimento de Software
description: Pra lembrar do que jรก foi.
paginate: 5
